// BYO fal.ai provider — image generation only (text/copy still goes through openai/mock).
// Returns BOTH a public CDN URL (used by the publisher to post images) and a local
// path (downloaded for /sns-preview).
//
// Env: FAL_KEY (required), FAL_IMAGE_MODEL (default fal-ai/flux-pro/v1.1)
// Docs: https://fal.ai/models  ·  https://docs.fal.ai/

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Buffer } from 'node:buffer';
import { provider as anthropic } from './anthropic.mjs';
import { assertProvider } from '../provider.mjs';

const ROOT = resolve(new URL('.', import.meta.url).pathname, '../../../..');
const KEY = () => process.env.FAL_KEY ?? '';
const IMAGE_MODEL = () => process.env.FAL_IMAGE_MODEL ?? 'fal-ai/flux-pro/v1.1';

// flux/schnell=4 steps (fast), flux/dev=28 (balanced), flux-pro=25 (quality)
function inferenceSteps(model) {
  if (model.includes('schnell')) return 4;
  if (model.includes('dev')) return 28;
  return 25;
}

// fal accepts either a string preset or a {width, height} object.
// Use exact SNS dimensions for best results.
function imageSize(aspect) {
  switch (aspect) {
    case 'portrait':  return { width: 1080, height: 1350 }; // 4:5 — Threads/Instagram feed
    case 'landscape': return 'landscape_16_9';
    case 'story':     return { width: 1080, height: 1920 }; // 9:16 — stories/reels
    default:          return 'square_hd';                   // 1080x1080
  }
}

export const provider = assertProvider({
  id: 'fal',
  byok: true,

  // fal.ai is image-first; copy is generated by Claude (Anthropic API).
  async generateCopy(req) {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error('fal provider는 카피 생성에 ANTHROPIC_API_KEY 가 필요합니다. .env.local 에 추가하세요.');
    }
    return anthropic.generateCopy(req);
  },

  async generateImage(req) {
    if (!KEY()) throw new Error('FAL_KEY not set');
    const t0 = Date.now();
    const model = IMAGE_MODEL();

    const steps = inferenceSteps(model);
    const body = {
      prompt: req.prompt,
      image_size: imageSize(req.aspect),
      num_images: req.count ?? 1,
      num_inference_steps: steps,
      guidance_scale: 3.5,
      enable_safety_checker: true,
    };

    const json = await falPost(`https://fal.run/${model}`, body);

    // Response shape: { images: [{ url, width, height, content_type, file_name }], ... }
    const images = json.images ?? [];
    if (!images.length) throw new Error('fal returned no images: ' + JSON.stringify(json).slice(0, 300));

    const dir = resolve(ROOT, 'out/fal-images');
    mkdirSync(dir, { recursive: true });

    const paths = [];
    const urls  = [];
    for (const [i, img] of images.entries()) {
      const url = img.url;
      urls.push(url);
      // Download a local copy so /sns-preview can show something even when offline later.
      try {
        const r = await fetch(url);
        if (r.ok) {
          const ext = (img.content_type ?? 'image/png').split('/')[1] ?? 'png';
          const file = resolve(dir, `${Date.now()}-${i}.${ext}`);
          writeFileSync(file, Buffer.from(await r.arrayBuffer()));
          paths.push(file.replace(ROOT + '/', ''));
        }
      } catch {
        // If the download fails the URL is still authoritative; preview just won't have a local path.
      }
    }

    return {
      paths,
      urls,
      meta: { provider: 'fal', model, latencyMs: Date.now() - t0 },
    };
  },

  healthcheck() {
    if (!KEY()) return { ok: false, reason: 'FAL_KEY not set' };
    return { ok: true };
  },
});

async function falPost(url, body, attempt = 1) {
  const r = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Key ${KEY()}` },
    body: JSON.stringify(body),
  });
  if (r.ok) return r.json();

  // Retry once on 429 / 5xx with linear backoff. fal occasionally cold-starts.
  if (attempt === 1 && (r.status === 429 || r.status >= 500)) {
    await new Promise((res) => setTimeout(res, 1500));
    return falPost(url, body, 2);
  }

  const text = await r.text();
  throw new Error(`fal HTTP ${r.status}: ${text.slice(0, 300)}`);
}
